import {
  UserProfile,
  PostItem,
  CommentItem,
  ActivityDistribution,
  TimelineEvent,
  AIInsight,
} from "@/types";

/**
 * SAMPLE / DEVELOPMENT DATA FOR MILESTONE 1
 * Modeled after the approved Stitch screens for u/Speeder.
 */

export const SAMPLE_PROFILE: UserProfile = {
  id: "c1f7a012-3844-4672-9118-e8ab11649980",
  redditId: "t2_123456",
  username: "Speeder",
  avatarUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuARgzaKrUrVpaJu2x5XSM2X3ZKfMqtCsye7uBlWpsLlw-kl06veZI1btYogzMzemMG945G6UelLq2Zh7yYZzVhBK5Z9qPLpJZqHRL_BQamXvUSyqHgW1b4_gFs14hhSh-v1nGZw5bsxNjTomsu-eRB3VYUIaTCFF1OjqMn-FaXQ4w8Wbxd03pu645j7gCP2Se8euSPxR_ZcsZuRNt4xbMG-JLLJOasSbeDLVT_HhF2Emff_A1A6CdQ",
  createdUtc: "2018-04-12T14:32:00Z",
  accountAgeYears: 6,
  firstSeenUtc: "2018-04-12T14:32:00Z",
  lastSeenUtc: "2024-08-29T19:10:00Z",
  totalKarma: 48290,
  linkKarma: 14200,
  commentKarma: 34090,
  syncStatus: "COMPLETED",
  syncProgress: 100,
  lastSyncedAt: "2026-09-01T12:00:00Z",
  metrics: {
    totalPosts: 412,
    totalComments: 3890,
    deletedPosts: 14,
    deletedComments: 86,
    removedPosts: 22,
    removedComments: 45,
    editedPosts: 31,
    editedComments: 210,
  },
};

export const SAMPLE_POSTS: PostItem[] = [
  {
    id: "e4581f12-0941-4776-a077-511bbcf80199",
    redditId: "t3_xj9k2q",
    title: "Optimal APM for Zerg Early Game Macro",
    selftext: "I've been analyzing replays of top Korean GM players, and there's a distinct pattern in APM bursts during the first 3 minutes. It's not just spamming; it's highly rhythmic. Specifically, at the 1:45 mark (usually when the first Overlord completes and scouting pathing is adjusted), APM spikes to ~350 for about 4 seconds. This correlates exactly with the timing window to identify early Protoss adept timings. If you aren't hitting this rhythm, your macro slips exactly when you need to react.",
    subreddit: "starcraft",
    author: "Speeder",
    score: 1240,
    numComments: 342,
    createdUtc: "2023-09-14T11:20:00Z",
    editedUtc: "2023-09-14T13:45:00Z",
    status: "EDITED",
    mediaStatus: "MEDIA_REFERENCE_ONLY",
    permalink: "/r/starcraft/comments/xj9k2q/optimal_apm_for_zerg_early_game_macro/",
  },
  {
    id: "f8174b21-8199-4112-b011-889911223344",
    redditId: "t3_k81mno",
    title: "[Removed by Moderator] Analysis of private tournament server exploits",
    selftext: "[Content removed by r/starcraft moderators due to rule 4: Exploit discussion]",
    subreddit: "starcraft",
    author: "Speeder",
    score: 412,
    numComments: 89,
    createdUtc: "2022-11-04T08:15:00Z",
    status: "REMOVED",
    mediaStatus: "MEDIA_UNAVAILABLE",
    permalink: "/r/starcraft/comments/k81mno/analysis_of_private_tournament_server_exploits/",
  },
  {
    id: "a9918233-1122-4455-8899-778899aabbcc",
    redditId: "t3_m9901x",
    title: "Why memory allocation patterns in modern game engines favor arena allocators",
    selftext: "In our high-performance game backend services, standard heap allocations were causing unbearable tail latencies during physics sync intervals. Switching to per-frame arena allocators reduced our 99th percentile frame latency from 18ms down to 3.2ms. Here is the architecture overview and benchmark results across 64-player concurrent matches.",
    subreddit: "programming",
    author: "Speeder",
    score: 2890,
    numComments: 410,
    createdUtc: "2021-06-20T19:40:00Z",
    status: "VISIBLE",
    mediaStatus: "MEDIA_AVAILABLE",
    permalink: "/r/programming/comments/m9901x/why_memory_allocation_patterns_in_modern_game/",
  },
  {
    id: "b1122334-5566-7788-99aa-bbccddeeff00",
    redditId: "t3_del110",
    title: "[Deleted by User] Personal thoughts on the regional tech hiring slowdown",
    selftext: "[Content deleted by author]",
    subreddit: "cscareerquestions",
    author: "Speeder",
    score: 85,
    numComments: 42,
    createdUtc: "2020-03-12T14:10:00Z",
    status: "DELETED",
    mediaStatus: "MEDIA_UNAVAILABLE",
    permalink: "/r/cscareerquestions/comments/del110/personal_thoughts_on_the_regional_tech_hiring/",
  },
];

export const SAMPLE_COMMENTS: CommentItem[] = [
  {
    id: "c001",
    redditId: "t1_gm7n8x9",
    postRedditId: "t3_k81mno",
    parentRedditId: "t1_gm7m110",
    subreddit: "rust",
    author: "Speeder",
    score: 85,
    createdUtc: "2024-02-18T16:45:00Z",
    editedUtc: "2024-02-18T17:10:00Z",
    status: "EDITED",
    body: "The borrow checker prevents this exact race condition at compile time. If you use Arc<Mutex<T>> you are paying for runtime synchronization overhead, but crossbeam channels give you lock-free ring-buffered queues that fit the actor pipeline much better.",
    parentContext: {
      author: "async_coder",
      bodySnippet: "Why can't I just pass a mutable reference to both threads if I know they won't write at the same time?",
    },
  },
  {
    id: "c002",
    redditId: "t1_gm8821a",
    postRedditId: "t3_xj9k2q",
    parentRedditId: "t3_xj9k2q",
    subreddit: "starcraft",
    author: "Speeder",
    score: 312,
    createdUtc: "2023-09-14T12:05:00Z",
    status: "VISIBLE",
    body: "Yes, exactly. Maru does this consistently in his early reaper micro too. The APM spikes aren't just jitter; they represent a mental check-routine cycle that resets every 15 seconds.",
  },
  {
    id: "c003",
    redditId: "t1_del4411",
    postRedditId: "t3_del110",
    parentRedditId: "t3_del110",
    subreddit: "cscareerquestions",
    author: "Speeder",
    score: 14,
    createdUtc: "2020-03-12T14:35:00Z",
    status: "DELETED",
    body: "[Comment deleted by user]",
  },
];

export const SAMPLE_ACTIVITY: ActivityDistribution = {
  topSubreddits: [
    { name: "starcraft", count: 1420, score: 22400, percentage: 36.5 },
    { name: "programming", count: 890, score: 11200, percentage: 22.9 },
    { name: "rust", count: 640, score: 8900, percentage: 16.4 },
    { name: "games", count: 510, score: 3400, percentage: 13.1 },
    { name: "cscareerquestions", count: 430, score: 2390, percentage: 11.1 },
  ],
  yearlyActivity: [
    { year: 2018, posts: 42, comments: 290 },
    { year: 2019, posts: 68, comments: 450 },
    { year: 2020, posts: 95, comments: 720 },
    { year: 2021, posts: 84, comments: 890 },
    { year: 2022, posts: 51, comments: 640 },
    { year: 2023, posts: 48, comments: 580 },
    { year: 2024, posts: 24, comments: 320 },
  ],
  hourlyActivityUtc: [
    { hour: 0, count: 120 },
    { hour: 2, count: 45 },
    { hour: 4, count: 15 },
    { hour: 6, count: 10 },
    { hour: 8, count: 85 },
    { hour: 10, count: 190 },
    { hour: 12, count: 280 },
    { hour: 14, count: 410 },
    { hour: 16, count: 520 },
    { hour: 18, count: 490 },
    { hour: 20, count: 390 },
    { hour: 22, count: 240 },
  ],
  dailyActivity: [
    { day: "Sun", count: 680 },
    { day: "Mon", count: 510 },
    { day: "Tue", count: 490 },
    { day: "Wed", count: 540 },
    { day: "Thu", count: 560 },
    { day: "Fri", count: 590 },
    { day: "Sat", count: 720 },
  ],
};

export const SAMPLE_TIMELINE: TimelineEvent[] = [
  {
    id: "tl-2024-1",
    year: 2024,
    dateStr: "Feb 18, 2024",
    type: "COMMENT",
    title: "Rust concurrency analysis",
    subreddit: "rust",
    status: "EDITED",
    snippet: "The borrow checker prevents this exact race condition at compile time...",
    score: 85,
    redditId: "t1_gm7n8x9",
  },
  {
    id: "tl-2023-1",
    year: 2023,
    dateStr: "Sep 14, 2023",
    type: "POST",
    title: "Optimal APM for Zerg Early Game Macro",
    subreddit: "starcraft",
    status: "EDITED",
    snippet: "Detailed breakdown of APM bursts during the first 3 minutes of play...",
    score: 1240,
    redditId: "t3_xj9k2q",
  },
  {
    id: "tl-2022-1",
    year: 2022,
    dateStr: "Nov 04, 2022",
    type: "POST",
    title: "Analysis of private tournament server exploits",
    subreddit: "starcraft",
    status: "REMOVED",
    snippet: "[Content removed by moderators for exploit discussion]",
    score: 412,
    redditId: "t3_k81mno",
  },
  {
    id: "tl-2021-1",
    year: 2021,
    dateStr: "Jun 20, 2021",
    type: "POST",
    title: "Why memory allocation patterns in modern game engines favor arena allocators",
    subreddit: "programming",
    status: "VISIBLE",
    snippet: "Switching to per-frame arena allocators reduced latency from 18ms to 3.2ms...",
    score: 2890,
    redditId: "t3_m9901x",
  },
  {
    id: "tl-2018-1",
    year: 2018,
    dateStr: "Apr 12, 2018",
    type: "MILESTONE",
    title: "Account Registered & First Recorded Activity",
    subreddit: "reddit",
    status: "VISIBLE",
    snippet: "First recorded timestamp captured in historical archive.",
    score: 1,
    redditId: "t2_123456",
  },
];

export const SAMPLE_AI_INSIGHTS: AIInsight[] = [
  {
    index: 1,
    category: "TECH_PROFESSION",
    title: "Systems-Level Software Engineer with Low-Level Focus",
    finding: "Repeated technical discussions on arena memory allocators, lock-free queues, and compiler guarantees indicate active professional work in systems or game engine development.",
    confidence: "HIGH",
    classification: "EXPLICIT",
    reasoning: "Explicitly states 'In our high-performance game backend services...' and detailed explanations of custom arena allocation implementations.",
    evidenceIds: ["t3_m9901x"],
    supportingCitations: [
      {
        redditId: "t3_m9901x",
        subreddit: "programming",
        sourceType: "POST",
        quote: "In our high-performance game backend services, standard heap allocations were causing unbearable tail latencies during physics sync intervals.",
        score: 2890,
        createdUtc: "2021-06-20T19:40:00Z",
        status: "VISIBLE",
      },
    ],
  },
  {
    index: 2,
    category: "GAMING_BEHAVIOR",
    title: "Competitive RTS Enthusiast (Zerg Faction Specialist)",
    finding: "Extensive analytical submissions in r/starcraft demonstrating deep knowledge of build orders, APM burst rhythms, and matchup timings.",
    confidence: "HIGH",
    classification: "STRONGLY_SUPPORTED",
    reasoning: "Submissions detailing specific Korean GM replay analysis at specific timestamps (1:45 mark) with Zerg scouting routines.",
    evidenceIds: ["t3_xj9k2q"],
    supportingCitations: [
      {
        redditId: "t3_xj9k2q",
        subreddit: "starcraft",
        sourceType: "POST",
        quote: "Specifically, at the 1:45 mark (usually when the first Overlord completes and scouting pathing is adjusted), APM spikes to ~350 for about 4 seconds.",
        score: 1240,
        createdUtc: "2023-09-14T11:20:00Z",
        status: "EDITED",
      },
    ],
  },
  {
    index: 3,
    category: "BEHAVIORAL_TRAITS",
    title: "Active Revision & Archival Deletion Habit",
    finding: "User demonstrates a consistent pattern of editing technical submissions after initial engagement, along with periodic deletion of career/personal inquiries.",
    confidence: "MEDIUM",
    classification: "WEAK_INFERENCE",
    reasoning: "Provenance logs show multiple revisions adding benchmark timestamps, combined with deleted threads in r/cscareerquestions during 2020.",
    evidenceIds: ["t3_xj9k2q", "t3_del110"],
    supportingCitations: [
      {
        redditId: "t3_del110",
        subreddit: "cscareerquestions",
        sourceType: "POST",
        quote: "[Content deleted by author]",
        score: 85,
        createdUtc: "2020-03-12T14:10:00Z",
        status: "DELETED",
      },
    ],
  },
];
